import 'dotenv/config';
import { type ChildProcess, execFileSync, spawn } from 'node:child_process';
import { randomBytes } from 'node:crypto';
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { Secp256k1Keypair } from '@atproto/crypto';
import dotenv from 'dotenv';
import type { PdsSettings } from './config-manager.js';
import { DATA_DIR } from './storage-paths.js';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
// Same depth from src/ and from dist/ after tsc build. The PDS runs from its
// own subpackage with an isolated node_modules: its dependency tree (express 4,
// undici 8) conflicts with the main app's, and undici 8 cannot load under bun.
const APP_ROOT_DIR = path.join(__dirname, '..');
const PDS_SERVICE_DIR = path.join(APP_ROOT_DIR, 'pds-service');
const PDS_SERVICE_ENTRY = path.join(PDS_SERVICE_DIR, 'index.mjs');

export const PDS_DATA_DIR = path.join(DATA_DIR, 'pds');
export const PDS_DEFAULT_PORT = 3010;

const PDS_SECRET_KEYS = ['PDS_JWT_SECRET', 'PDS_ADMIN_PASSWORD', 'PDS_PLC_ROTATION_KEY_K256_PRIVATE_KEY_HEX'] as const;
type PdsSecretKey = (typeof PDS_SECRET_KEYS)[number];
export type PdsSecrets = Record<PdsSecretKey, string>;

export interface PdsHandle {
  port: number;
  hostname: string;
  localUrl: string;
  stop: () => Promise<void>;
}

export interface ProvisionResult {
  twitterUsername: string;
  handle: string;
  did: string;
  password: string;
  existing: boolean;
}

export type ProvisionProgress = (step: string) => void;

// Anchored to the app root like every other path in the repo (see
// storage-paths.ts), so running the CLI from a subdirectory still writes to the
// .env that `bun start` will actually read.
const ENV_FILE = path.join(APP_ROOT_DIR, '.env');

// `import 'dotenv/config'` above resolves against process.cwd(); load the
// app-root file too so reads and writes target the same .env regardless of cwd.
// dotenv never overrides already-set vars, so this is a no-op in the normal case
// where cwd is the app root.
dotenv.config({ path: ENV_FILE, quiet: true });

// ---------------------------------------------------------------------------
// Secrets
// ---------------------------------------------------------------------------

export async function generateMissingPdsSecrets(envFile = ENV_FILE): Promise<{
  secrets: PdsSecrets;
  generated: PdsSecretKey[];
}> {
  const generated: PdsSecretKey[] = [];
  const secrets = {} as PdsSecrets;

  // Keys already present in the .env text (even with an empty value) must be
  // rewritten in place rather than appended, or the file accumulates duplicate
  // assignments and the last one silently wins.
  const existingEnvText = fs.existsSync(envFile) ? fs.readFileSync(envFile, 'utf8') : '';
  const keyIsDeclaredInFile = (key: PdsSecretKey) =>
    new RegExp(`^[ \\t]*(?:export[ \\t]+)?${key}[ \\t]*=`, 'm').test(existingEnvText);
  const rewrittenInPlace: PdsSecretKey[] = [];

  for (const key of PDS_SECRET_KEYS) {
    const existing = process.env[key]?.trim();
    if (existing) {
      secrets[key] = existing;
      continue;
    }

    let value: string;
    if (key === 'PDS_PLC_ROTATION_KEY_K256_PRIVATE_KEY_HEX') {
      const keypair = await Secp256k1Keypair.create({ exportable: true });
      value = Buffer.from(await keypair.export()).toString('hex');
    } else {
      value = randomBytes(24).toString('hex');
    }
    secrets[key] = value;
    process.env[key] = value;
    generated.push(key);
    if (keyIsDeclaredInFile(key)) {
      rewrittenInPlace.push(key);
    }
  }

  if (generated.length > 0) {
    let text = existingEnvText;
    for (const key of rewrittenInPlace) {
      text = text.replace(new RegExp(`^[ \\t]*(?:export[ \\t]+)?${key}[ \\t]*=.*$`, 'm'), `${key}=${secrets[key]}`);
    }
    const appended = generated.filter((key) => !rewrittenInPlace.includes(key));
    if (appended.length > 0) {
      const header = '\n# Built-in PDS secrets (generated by setup-pds; do not share)\n';
      const lines = appended.map((key) => `${key}=${secrets[key]}`);
      text = `${text}${header}${lines.join('\n')}\n`;
    }
    fs.writeFileSync(envFile, text);
  }

  return { secrets, generated };
}

export function getPdsSecrets(): PdsSecrets | null {
  const secrets = {} as PdsSecrets;
  for (const key of PDS_SECRET_KEYS) {
    const value = process.env[key]?.trim();
    if (!value) return null;
    secrets[key] = value;
  }
  return secrets;
}

// ---------------------------------------------------------------------------
// Server lifecycle
// ---------------------------------------------------------------------------

// Mirrors DISALLOWED_TLDS in @atproto/syntax. Handles under these TLDs are
// rejected by the PDS at account creation ("Handle TLD is invalid or
// disallowed"), so a PDS hostname ending in one can never provision an account.
// ".test" is deliberately absent: atproto allows it for local development.
const DISALLOWED_HANDLE_TLDS = [
  '.local',
  '.arpa',
  '.invalid',
  '.localhost',
  '.internal',
  '.example',
  '.alt',
  '.onion',
] as const;

// A ".test" hostname is the only supported way to run the PDS without public
// DNS or TLS. Plain "localhost" does NOT work: @atproto/pds forces
// serviceHandleDomains to [".test"] for that hostname, and ".localhost" is a
// disallowed handle TLD besides.
export const isDevPdsHostname = (hostname: string) => hostname === 'test' || hostname.endsWith('.test');

// Rejects hostnames that cannot host atproto handles, with the reason, before
// the wizard spends time generating secrets and booting a server.
export function validatePdsHostname(hostname: string): { ok: true } | { ok: false; reason: string } {
  const normalized = hostname.trim().toLowerCase();
  if (!normalized) {
    return { ok: false, reason: 'Hostname is required.' };
  }
  if (normalized === 'localhost') {
    return {
      ok: false,
      reason:
        'The hostname "localhost" cannot host atproto handles: @atproto/pds restricts it to ".test" handles, and ".localhost" is a disallowed handle TLD. Use a ".test" hostname for local runs (for example "t2b.test") or a real domain you control.',
    };
  }
  const badTld = DISALLOWED_HANDLE_TLDS.find((tld) => normalized.endsWith(tld));
  if (badTld) {
    return {
      ok: false,
      reason: `Handles under "${badTld}" are rejected by the AT Protocol (reserved TLD). Use a ".test" hostname for local runs or a real domain you control.`,
    };
  }
  if (!normalized.includes('.')) {
    return {
      ok: false,
      reason: `"${normalized}" has no TLD, so handles like "someone.${normalized}" will never resolve. Use a ".test" hostname for local runs or a real domain you control.`,
    };
  }
  if (!/^[a-z0-9](?:[a-z0-9-]*[a-z0-9])?(?:\.[a-z0-9](?:[a-z0-9-]*[a-z0-9])?)+$/.test(normalized)) {
    return { ok: false, reason: `"${normalized}" is not a valid domain name.` };
  }
  return { ok: true };
}

export function assertValidPdsHostname(hostname: string): void {
  const result = validatePdsHostname(hostname);
  if (!result.ok) {
    throw new Error(result.reason);
  }
}

function buildPdsEnv(settings: PdsSettings, secrets: PdsSecrets): Record<string, string> {
  fs.mkdirSync(PDS_DATA_DIR, { recursive: true });
  fs.mkdirSync(path.join(PDS_DATA_DIR, 'blocks'), { recursive: true });

  const env: Record<string, string> = {
    PDS_HOSTNAME: settings.hostname,
    PDS_PORT: String(settings.port),
    PDS_DATA_DIRECTORY: PDS_DATA_DIR,
    PDS_BLOBSTORE_DISK_LOCATION: path.join(PDS_DATA_DIR, 'blocks'),
    PDS_BLOB_UPLOAD_LIMIT: '52428800',
    PDS_DID_PLC_URL: 'https://plc.directory',
    PDS_BSKY_APP_VIEW_URL: 'https://api.bsky.app',
    PDS_BSKY_APP_VIEW_DID: 'did:web:api.bsky.app',
    PDS_REPORT_SERVICE_URL: 'https://mod.bsky.app',
    PDS_REPORT_SERVICE_DID: 'did:plc:ar7c4by46qjdydhdevvrndac',
    PDS_CRAWLERS: 'https://bsky.network',
    PDS_INVITE_REQUIRED: 'true',
    LOG_ENABLED: process.env.PDS_LOG_ENABLED ?? 'false',
    // @atproto/pds calls app.listen(port) with no host, which binds 0.0.0.0 and
    // would expose the whole PDS over cleartext HTTP on a public IP, bypassing
    // the TLS proxy. pds-service/index.mjs binds this host instead. Override to
    // 0.0.0.0 only when the reverse proxy cannot reach loopback (e.g. Caddy in a
    // bridge-network container) — and firewall the port if you do.
    PDS_BIND_HOST: process.env.PDS_BIND_HOST?.trim() || '127.0.0.1',
    ...secrets,
  };

  if (isDevPdsHostname(settings.hostname)) {
    // Local/test mode: no public DNS or TLS available.
    env.PDS_DEV_MODE = 'true';
  }

  const smtpUrl = process.env.PDS_EMAIL_SMTP_URL?.trim();
  const fromAddress = process.env.PDS_EMAIL_FROM_ADDRESS?.trim();
  if (smtpUrl && fromAddress) {
    env.PDS_EMAIL_SMTP_URL = smtpUrl;
    env.PDS_EMAIL_FROM_ADDRESS = fromAddress;
  }

  return env;
}

// @atproto/pds depends on undici v8, which cannot load under bun — so the PDS
// runs as a Node child process while the rest of the app stays on bun.
function findNodeBinary(): string {
  const candidates = process.versions.bun ? ['node'] : [process.execPath, 'node'];
  for (const candidate of candidates) {
    try {
      const version = execFileSync(candidate, ['--version'], { encoding: 'utf8' }).trim();
      const major = Number.parseInt(version.replace(/^v/, '').split('.')[0] ?? '0', 10);
      if (major >= 22) return candidate;
      console.warn(`Found ${candidate} ${version}, but the built-in PDS needs Node 22+.`);
    } catch {
      // try next candidate
    }
  }
  throw new Error('Node.js 22+ is required to run the built-in PDS. Install it from https://nodejs.org.');
}

// Installs the PDS service dependencies on first use, with npm so native
// modules are built for the Node child process (not bun's ABI). Docker images
// pre-install these at build time, so this is a no-op there.
export function ensurePdsServiceDeps(): void {
  if (fs.existsSync(path.join(PDS_SERVICE_DIR, 'node_modules', '@atproto', 'pds'))) {
    return;
  }
  console.log('📦 Installing built-in PDS dependencies (first run only)...');
  try {
    execFileSync('npm', ['install', '--no-audit', '--no-fund'], {
      cwd: PDS_SERVICE_DIR,
      stdio: 'inherit',
    });
  } catch (error) {
    const code = (error as { code?: string }).code;
    if (code === 'ENOENT') {
      throw new Error(
        'npm was not found on PATH, so the built-in PDS dependencies cannot be installed. The PDS runs under Node.js (not bun) and needs its own node_modules — install Node.js 22+ (which ships npm) and re-run.',
      );
    }
    throw new Error(
      `Installing the built-in PDS dependencies failed (npm install in ${PDS_SERVICE_DIR}). Fix the npm error above, or run "npm install" in that directory manually, then retry.`,
    );
  }
}

export interface StartPdsOptions {
  // Restart the PDS if it dies unexpectedly. Long-running processes (`bun start`)
  // want this; short-lived CLI commands do not.
  superviseOnCrash?: boolean;
}

const PDS_RESTART_MIN_DELAY_MS = 1_000;
const PDS_RESTART_MAX_DELAY_MS = 60_000;
// Once the PDS has stayed up this long, treat the next crash as a fresh
// incident rather than continuing to back off.
const PDS_RESTART_BACKOFF_RESET_MS = 60_000;

export async function startPds(settings: PdsSettings, options: StartPdsOptions = {}): Promise<PdsHandle> {
  const secrets = getPdsSecrets();
  if (!secrets) {
    throw new Error('PDS secrets missing from environment. Run `bun run cli -- setup-pds` first.');
  }
  if (!fs.existsSync(PDS_SERVICE_ENTRY)) {
    throw new Error(
      `The built-in PDS runtime is missing from this install (expected ${PDS_SERVICE_ENTRY}). Reinstall from source, or run ./update.sh to pull it in.`,
    );
  }
  assertValidPdsHostname(settings.hostname);
  ensurePdsServiceDeps();

  const localUrl = `http://127.0.0.1:${settings.port}`;
  if (await isPdsHealthy(localUrl)) {
    throw new Error(`Port ${settings.port} is already serving a PDS. Use the running instance or stop it first.`);
  }

  const nodeBinary = findNodeBinary();
  const env = buildPdsEnv(settings, secrets);
  const logPath = path.join(PDS_DATA_DIR, 'pds.log');

  let child: ChildProcess | null = null;
  let stopping = false;
  let restartDelayMs = PDS_RESTART_MIN_DELAY_MS;
  let restartTimer: NodeJS.Timeout | null = null;

  // The PDS must never outlive the parent — an orphan would keep the port
  // busy and serve stale config to the next run.
  const killChildOnExit = () => {
    child?.kill('SIGTERM');
  };
  process.once('exit', killChildOnExit);

  const spawnChild = (): ChildProcess => {
    const logFd = fs.openSync(logPath, 'a');
    const spawned = spawn(nodeBinary, [PDS_SERVICE_ENTRY], {
      cwd: PDS_SERVICE_DIR,
      env: { ...process.env, ...env },
      stdio: ['ignore', logFd, logFd],
    });
    fs.closeSync(logFd);
    const startedAt = Date.now();

    spawned.on('exit', (code, signal) => {
      if (spawned !== child) {
        // Superseded by a restart; its exit is not interesting.
        return;
      }
      child = null;
      const deliberate = stopping || signal === 'SIGTERM' || signal === 'SIGINT';
      if (deliberate) {
        process.removeListener('exit', killChildOnExit);
        return;
      }

      console.error(`⚠️ Built-in PDS exited unexpectedly (code ${code}, signal ${signal}). See ${logPath}`);
      if (!options.superviseOnCrash) {
        console.error('⚠️ Mirroring will fail until the PDS is running again. Restart the app to bring it back.');
        process.removeListener('exit', killChildOnExit);
        return;
      }

      if (Date.now() - startedAt >= PDS_RESTART_BACKOFF_RESET_MS) {
        restartDelayMs = PDS_RESTART_MIN_DELAY_MS;
      }
      const delay = restartDelayMs;
      restartDelayMs = Math.min(restartDelayMs * 2, PDS_RESTART_MAX_DELAY_MS);
      console.error(`🛰️ Restarting the built-in PDS in ${Math.round(delay / 1000)}s...`);
      restartTimer = setTimeout(() => {
        restartTimer = null;
        if (stopping) return;
        child = spawnChild();
        void waitForPdsHealthy(localUrl, 30_000, () => child === null)
          .then(() => console.log('🛰️ Built-in PDS is healthy again.'))
          .catch((error) => console.error(`⚠️ Built-in PDS did not come back: ${(error as Error).message}`));
      }, delay);
    });

    return spawned;
  };

  child = spawnChild();

  try {
    await waitForPdsHealthy(localUrl, 30_000, () => child === null);
  } catch (error) {
    stopping = true;
    child?.kill('SIGTERM');
    process.removeListener('exit', killChildOnExit);
    throw new Error(`${(error as Error).message}. Check the PDS log: ${logPath}`);
  }

  return {
    port: settings.port,
    hostname: settings.hostname,
    localUrl,
    stop: async () => {
      stopping = true;
      if (restartTimer) {
        clearTimeout(restartTimer);
        restartTimer = null;
      }
      const current = child;
      process.removeListener('exit', killChildOnExit);
      if (!current) return;
      await new Promise<void>((resolve) => {
        const timeout = setTimeout(() => {
          current.kill('SIGKILL');
          resolve();
        }, 5_000);
        current.once('exit', () => {
          clearTimeout(timeout);
          resolve();
        });
        current.kill('SIGTERM');
      });
    },
  };
}

export async function isPdsHealthy(localUrl: string): Promise<boolean> {
  try {
    const res = await fetch(`${localUrl}/xrpc/_health`, { signal: AbortSignal.timeout(2_000) });
    return res.ok;
  } catch {
    return false;
  }
}

async function waitForPdsHealthy(localUrl: string, timeoutMs = 15_000, hasExited?: () => boolean): Promise<void> {
  const deadline = Date.now() + timeoutMs;
  while (Date.now() < deadline) {
    if (hasExited?.()) {
      throw new Error('PDS process exited before becoming healthy');
    }
    if (await isPdsHealthy(localUrl)) return;
    await new Promise((resolve) => setTimeout(resolve, 250));
  }
  throw new Error(`PDS did not become healthy at ${localUrl} within ${timeoutMs}ms`);
}

// ---------------------------------------------------------------------------
// Account provisioning
// ---------------------------------------------------------------------------

// @atproto/pds enforces these on the label in front of the service domain
// (ensureHandleServiceConstraints). Twitter caps usernames at 15 characters so
// the upper bound is unreachable in practice, but legacy 1-2 character handles
// do exist and would otherwise fail deep inside createAccount.
const PDS_LABEL_MIN_LENGTH = 3;
const PDS_LABEL_MAX_LENGTH = 18;

// Twitter usernames allow [A-Za-z0-9_], DNS labels do not allow "_". Handles
// like "some_user" become "some-user.example.com".
export function twitterHandleToPdsLabel(twitterUsername: string): string {
  const label = twitterUsername
    .trim()
    .replace(/^@/, '')
    .toLowerCase()
    .replace(/_/g, '-')
    .replace(/[^a-z0-9-]/g, '')
    .replace(/^-+|-+$/g, '');
  if (!label) {
    throw new Error(`Cannot derive a valid handle from Twitter username "${twitterUsername}"`);
  }
  if (label.length < PDS_LABEL_MIN_LENGTH) {
    throw new Error(
      `Twitter username "${twitterUsername}" maps to the handle label "${label}", which is shorter than the ${PDS_LABEL_MIN_LENGTH}-character minimum the AT Protocol enforces. Mirror this account to a manually created Bluesky account instead.`,
    );
  }
  if (label.length > PDS_LABEL_MAX_LENGTH) {
    throw new Error(
      `Twitter username "${twitterUsername}" maps to the handle label "${label}", which exceeds the ${PDS_LABEL_MAX_LENGTH}-character maximum the AT Protocol enforces.`,
    );
  }
  return label;
}

interface XrpcErrorBody {
  error?: string;
  message?: string;
}

async function xrpc<T>(
  localUrl: string,
  method: 'GET' | 'POST',
  nsid: string,
  options: { body?: unknown; adminPassword?: string; params?: Record<string, string> } = {},
): Promise<T> {
  const query = options.params ? `?${new URLSearchParams(options.params)}` : '';
  const headers: Record<string, string> = { 'Content-Type': 'application/json' };
  if (options.adminPassword) {
    headers.Authorization = `Basic ${Buffer.from(`admin:${options.adminPassword}`).toString('base64')}`;
  }
  const res = await fetch(`${localUrl}/xrpc/${nsid}${query}`, {
    method,
    headers,
    body: options.body === undefined ? undefined : JSON.stringify(options.body),
  });
  const data = (await res.json().catch(() => ({}))) as T & XrpcErrorBody;
  if (!res.ok) {
    const err = new Error(`${nsid} failed: ${data.message || data.error || res.status}`);
    (err as Error & { xrpcError?: string }).xrpcError = data.error;
    throw err;
  }
  return data;
}

interface SqliteDbLike {
  prepare: (sql: string) => { run: (...params: unknown[]) => unknown; get: (...params: unknown[]) => unknown };
  exec: (sql: string) => unknown;
  close: () => void;
}

// The PDS child process holds this database open in WAL mode and opens it with
// better-sqlite3's `timeout: 0`, handling contention with its own retry loop.
// Neither bun:sqlite nor better-sqlite3 sets a busy timeout by default, so
// without this an UPDATE landing during a PDS write fails immediately with
// SQLITE_BUSY.
const SQLITE_BUSY_TIMEOUT_MS = 5_000;

// Same runtime split as src/db.ts: bun:sqlite under bun (better-sqlite3's
// native module does not load there), better-sqlite3 under node.
export async function openSqliteDb(dbPath: string): Promise<SqliteDbLike> {
  let db: SqliteDbLike;
  if (typeof process.versions.bun === 'string') {
    const bunSqliteSpecifier = 'bun:sqlite';
    const sqliteModule = (await import(bunSqliteSpecifier)) as {
      Database: new (filename: string) => SqliteDbLike;
    };
    db = new sqliteModule.Database(dbPath);
  } else {
    const betterSqliteModule = await import('better-sqlite3');
    db = new betterSqliteModule.default(dbPath) as unknown as SqliteDbLike;
  }
  db.exec(`PRAGMA busy_timeout = ${SQLITE_BUSY_TIMEOUT_MS}`);
  return db;
}

// The account is created with a phony local email and then marked verified by
// writing emailConfirmedAt directly into the PDS account database — no real
// mailbox or SMTP setup is needed.
export async function markEmailConfirmed(did: string): Promise<void> {
  const accountDb = path.join(PDS_DATA_DIR, 'account.sqlite');
  if (!fs.existsSync(accountDb)) {
    throw new Error(`PDS account database not found at ${accountDb}`);
  }
  const backdated = new Date(Date.now() - 30 * 24 * 60 * 60 * 1000).toISOString();

  // busy_timeout covers the common case; the retry covers a write that spans
  // longer than the timeout (the PDS batches repo writes under load).
  const maxAttempts = 3;
  for (let attempt = 1; ; attempt += 1) {
    const db = await openSqliteDb(accountDb);
    try {
      db.prepare('UPDATE account SET emailConfirmedAt = ? WHERE did = ? AND emailConfirmedAt IS NULL').run(
        backdated,
        did,
      );
      return;
    } catch (error) {
      const message = error instanceof Error ? error.message : String(error);
      const isBusy = /SQLITE_BUSY|database is locked/i.test(message);
      if (!isBusy || attempt >= maxAttempts) {
        throw error;
      }
      await new Promise((resolve) => setTimeout(resolve, 250 * attempt));
    } finally {
      db.close();
    }
  }
}

export async function provisionPdsAccount(
  settings: PdsSettings,
  twitterUsername: string,
  onProgress: ProvisionProgress = () => {},
): Promise<ProvisionResult> {
  const secrets = getPdsSecrets();
  if (!secrets) {
    throw new Error('PDS secrets missing from environment. Run `bun run cli -- setup-pds` first.');
  }
  const adminPassword = secrets.PDS_ADMIN_PASSWORD;
  const localUrl = `http://127.0.0.1:${settings.port}`;

  const label = twitterHandleToPdsLabel(twitterUsername);
  const handle = `${label}.${settings.hostname}`;
  // Phony address; never receives mail (verification is backdated in SQL).
  // The PDS validates email syntax including TLD, so ".test" hostnames fall back
  // to example.com.
  const emailDomain =
    settings.hostname.includes('.') && !isDevPdsHostname(settings.hostname) ? settings.hostname : 'example.com';
  const email = `${label}@${emailDomain}`;
  const password = randomBytes(18).toString('base64url');

  onProgress('Creating invite code');
  const invite = await xrpc<{ code: string }>(localUrl, 'POST', 'com.atproto.server.createInviteCode', {
    body: { useCount: 1 },
    adminPassword,
  });

  onProgress(`Creating account ${handle}`);
  try {
    const created = await xrpc<{ did: string }>(localUrl, 'POST', 'com.atproto.server.createAccount', {
      body: { email, handle, password, inviteCode: invite.code },
    });

    onProgress('Marking email as verified (backdated)');
    await markEmailConfirmed(created.did);

    return { twitterUsername, handle, did: created.did, password, existing: false };
  } catch (error) {
    const { xrpcError } = error as Error & { xrpcError?: string };
    const message = error instanceof Error ? error.message : '';
    const handleTaken =
      xrpcError === 'HandleNotAvailable' || xrpcError === 'AlreadyExists' || message.includes('Handle already taken');
    if (!handleTaken) {
      // The handle is free but the address is spoken for: an earlier account was
      // renamed away from this handle and still holds the derived email. Nothing
      // here can recover it automatically, so say what to do about it.
      if (message.includes('Email already taken')) {
        throw new Error(
          `The address ${email} is already registered on this PDS under a different handle (an account was probably renamed). Delete or re-point that account with the PDS admin API, then re-run this command.`,
        );
      }
      throw error;
    }

    // Account already exists (e.g. wizard re-run). Reset its password via the
    // admin API so we always end up with working credentials.
    onProgress(`Account ${handle} already exists — resetting password`);
    const resolved = await xrpc<{ did: string }>(localUrl, 'GET', 'com.atproto.identity.resolveHandle', {
      params: { handle },
    });
    await xrpc(localUrl, 'POST', 'com.atproto.admin.updateAccountPassword', {
      body: { did: resolved.did, password },
      adminPassword,
    });

    onProgress('Marking email as verified (backdated)');
    await markEmailConfirmed(resolved.did);

    return { twitterUsername, handle, did: resolved.did, password, existing: true };
  }
}

// ---------------------------------------------------------------------------
// Caddyfile generation (public deployments)
// ---------------------------------------------------------------------------

// Proxies to localhost because the PDS binds 127.0.0.1 by default (see
// PDS_BIND_HOST in buildPdsEnv). Caddy must therefore share the host's network
// namespace — hence the `--network host` hint in the setup output.
export function writeCaddyfile(settings: PdsSettings, contactEmail?: string): string {
  fs.mkdirSync(PDS_DATA_DIR, { recursive: true });
  const caddyfile = path.join(PDS_DATA_DIR, 'Caddyfile');
  const emailLine = contactEmail ? `\temail ${contactEmail}\n` : '';
  fs.writeFileSync(
    caddyfile,
    `{\n${emailLine}\ton_demand_tls {\n\t\task http://localhost:${settings.port}/tls-check\n\t}\n}\n\n` +
      `*.${settings.hostname}, ${settings.hostname} {\n\ttls {\n\t\ton_demand\n\t}\n\treverse_proxy http://localhost:${settings.port}\n}\n`,
  );
  return caddyfile;
}
