import 'dotenv/config';
import { type ChildProcess, execFileSync, spawn } from 'node:child_process';
import { randomBytes } from 'node:crypto';
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { Secp256k1Keypair } from '@atproto/crypto';
import type { PdsSettings } from './config-manager.js';
import { DATA_DIR } from './storage-paths.js';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
// Same depth from src/ and from dist/ after tsc build. The PDS runs from its
// own subpackage with an isolated node_modules: its dependency tree (express 4,
// undici 8) conflicts with the main app's, and undici 8 cannot load under bun.
const PDS_SERVICE_DIR = path.join(__dirname, '..', 'pds-service');
const PDS_SERVICE_ENTRY = path.join(PDS_SERVICE_DIR, 'index.mjs');

export const PDS_DATA_DIR = path.join(DATA_DIR, 'pds');
export const PDS_DEFAULT_PORT = 3010;

const PDS_SECRET_KEYS = ['PDS_JWT_SECRET', 'PDS_ADMIN_PASSWORD', 'PDS_PLC_ROTATION_KEY_K256_PRIVATE_KEY_HEX'] as const;
type PdsSecretKey = (typeof PDS_SECRET_KEYS)[number];
export type PdsSecrets = Record<PdsSecretKey, string>;

export interface PdsHandle {
  port: number;
  hostname: string;
  localUrl: string;
  stop: () => Promise<void>;
}

export interface ProvisionResult {
  twitterUsername: string;
  handle: string;
  did: string;
  password: string;
  existing: boolean;
}

export type ProvisionProgress = (step: string) => void;

// Matches where `import 'dotenv/config'` loads from.
const ENV_FILE = path.resolve(process.cwd(), '.env');

// ---------------------------------------------------------------------------
// Secrets
// ---------------------------------------------------------------------------

export async function generateMissingPdsSecrets(envFile = ENV_FILE): Promise<{
  secrets: PdsSecrets;
  generated: PdsSecretKey[];
}> {
  const generated: PdsSecretKey[] = [];
  const secrets = {} as PdsSecrets;

  for (const key of PDS_SECRET_KEYS) {
    const existing = process.env[key]?.trim();
    if (existing) {
      secrets[key] = existing;
      continue;
    }

    let value: string;
    if (key === 'PDS_PLC_ROTATION_KEY_K256_PRIVATE_KEY_HEX') {
      const keypair = await Secp256k1Keypair.create({ exportable: true });
      value = Buffer.from(await keypair.export()).toString('hex');
    } else {
      value = randomBytes(24).toString('hex');
    }
    secrets[key] = value;
    process.env[key] = value;
    generated.push(key);
  }

  if (generated.length > 0) {
    const lines = generated.map((key) => `${key}=${secrets[key]}`);
    const header = '\n# Built-in PDS secrets (generated by setup-pds; do not share)\n';
    fs.appendFileSync(envFile, `${header}${lines.join('\n')}\n`);
  }

  return { secrets, generated };
}

export function getPdsSecrets(): PdsSecrets | null {
  const secrets = {} as PdsSecrets;
  for (const key of PDS_SECRET_KEYS) {
    const value = process.env[key]?.trim();
    if (!value) return null;
    secrets[key] = value;
  }
  return secrets;
}

// ---------------------------------------------------------------------------
// Server lifecycle
// ---------------------------------------------------------------------------

const isLocalHostname = (hostname: string) =>
  hostname === 'localhost' || hostname.endsWith('.localhost') || hostname.endsWith('.test');

function buildPdsEnv(settings: PdsSettings, secrets: PdsSecrets): Record<string, string> {
  fs.mkdirSync(PDS_DATA_DIR, { recursive: true });
  fs.mkdirSync(path.join(PDS_DATA_DIR, 'blocks'), { recursive: true });

  const env: Record<string, string> = {
    PDS_HOSTNAME: settings.hostname,
    PDS_PORT: String(settings.port),
    PDS_DATA_DIRECTORY: PDS_DATA_DIR,
    PDS_BLOBSTORE_DISK_LOCATION: path.join(PDS_DATA_DIR, 'blocks'),
    PDS_BLOB_UPLOAD_LIMIT: '52428800',
    PDS_DID_PLC_URL: 'https://plc.directory',
    PDS_BSKY_APP_VIEW_URL: 'https://api.bsky.app',
    PDS_BSKY_APP_VIEW_DID: 'did:web:api.bsky.app',
    PDS_REPORT_SERVICE_URL: 'https://mod.bsky.app',
    PDS_REPORT_SERVICE_DID: 'did:plc:ar7c4by46qjdydhdevvrndac',
    PDS_CRAWLERS: 'https://bsky.network',
    PDS_INVITE_REQUIRED: 'true',
    LOG_ENABLED: process.env.PDS_LOG_ENABLED ?? 'false',
    ...secrets,
  };

  if (isLocalHostname(settings.hostname)) {
    // Local/test mode: no public DNS or TLS available.
    env.PDS_DEV_MODE = 'true';
  }

  const smtpUrl = process.env.PDS_EMAIL_SMTP_URL?.trim();
  const fromAddress = process.env.PDS_EMAIL_FROM_ADDRESS?.trim();
  if (smtpUrl && fromAddress) {
    env.PDS_EMAIL_SMTP_URL = smtpUrl;
    env.PDS_EMAIL_FROM_ADDRESS = fromAddress;
  }

  return env;
}

// @atproto/pds depends on undici v8, which cannot load under bun — so the PDS
// runs as a Node child process while the rest of the app stays on bun.
function findNodeBinary(): string {
  const candidates = process.versions.bun ? ['node'] : [process.execPath, 'node'];
  for (const candidate of candidates) {
    try {
      const version = execFileSync(candidate, ['--version'], { encoding: 'utf8' }).trim();
      const major = Number.parseInt(version.replace(/^v/, '').split('.')[0] ?? '0', 10);
      if (major >= 22) return candidate;
      console.warn(`Found ${candidate} ${version}, but the built-in PDS needs Node 22+.`);
    } catch {
      // try next candidate
    }
  }
  throw new Error('Node.js 22+ is required to run the built-in PDS. Install it from https://nodejs.org.');
}

// Installs the PDS service dependencies on first use, with npm so native
// modules are built for the Node child process (not bun's ABI).
export function ensurePdsServiceDeps(): void {
  if (fs.existsSync(path.join(PDS_SERVICE_DIR, 'node_modules', '@atproto', 'pds'))) {
    return;
  }
  console.log('📦 Installing built-in PDS dependencies (first run only)...');
  execFileSync('npm', ['install', '--no-audit', '--no-fund'], {
    cwd: PDS_SERVICE_DIR,
    stdio: 'inherit',
  });
}

export async function startPds(settings: PdsSettings): Promise<PdsHandle> {
  const secrets = getPdsSecrets();
  if (!secrets) {
    throw new Error('PDS secrets missing from environment. Run `bun run cli -- setup-pds` first.');
  }
  if (!fs.existsSync(PDS_SERVICE_ENTRY)) {
    throw new Error(`PDS service entry not found at ${PDS_SERVICE_ENTRY}`);
  }
  ensurePdsServiceDeps();

  const localUrlPrecheck = `http://127.0.0.1:${settings.port}`;
  if (await isPdsHealthy(localUrlPrecheck)) {
    throw new Error(`Port ${settings.port} is already serving a PDS. Use the running instance or stop it first.`);
  }

  const nodeBinary = findNodeBinary();
  const env = buildPdsEnv(settings, secrets);
  const logPath = path.join(PDS_DATA_DIR, 'pds.log');
  const logFd = fs.openSync(logPath, 'a');

  const child: ChildProcess = spawn(nodeBinary, [PDS_SERVICE_ENTRY], {
    cwd: PDS_SERVICE_DIR,
    env: { ...process.env, ...env },
    stdio: ['ignore', logFd, logFd],
  });
  fs.closeSync(logFd);

  // The PDS must never outlive the parent — an orphan would keep the port
  // busy and serve stale config to the next run.
  const killChildOnExit = () => {
    child.kill('SIGTERM');
  };
  process.once('exit', killChildOnExit);

  let exited = false;
  child.on('exit', (code, signal) => {
    exited = true;
    process.removeListener('exit', killChildOnExit);
    if (code !== 0 && signal !== 'SIGTERM' && signal !== 'SIGINT') {
      console.error(`⚠️ Built-in PDS exited unexpectedly (code ${code}, signal ${signal}). See ${logPath}`);
    }
  });

  const localUrl = `http://127.0.0.1:${settings.port}`;
  try {
    await waitForPdsHealthy(localUrl, 30_000, () => exited);
  } catch (error) {
    child.kill('SIGTERM');
    throw new Error(`${(error as Error).message}. Check the PDS log: ${logPath}`);
  }

  return {
    port: settings.port,
    hostname: settings.hostname,
    localUrl,
    stop: async () => {
      if (exited) return;
      await new Promise<void>((resolve) => {
        const timeout = setTimeout(() => {
          child.kill('SIGKILL');
          resolve();
        }, 5_000);
        child.once('exit', () => {
          clearTimeout(timeout);
          resolve();
        });
        child.kill('SIGTERM');
      });
    },
  };
}

export async function isPdsHealthy(localUrl: string): Promise<boolean> {
  try {
    const res = await fetch(`${localUrl}/xrpc/_health`, { signal: AbortSignal.timeout(2_000) });
    return res.ok;
  } catch {
    return false;
  }
}

async function waitForPdsHealthy(localUrl: string, timeoutMs = 15_000, hasExited?: () => boolean): Promise<void> {
  const deadline = Date.now() + timeoutMs;
  while (Date.now() < deadline) {
    if (hasExited?.()) {
      throw new Error('PDS process exited before becoming healthy');
    }
    if (await isPdsHealthy(localUrl)) return;
    await new Promise((resolve) => setTimeout(resolve, 250));
  }
  throw new Error(`PDS did not become healthy at ${localUrl} within ${timeoutMs}ms`);
}

// ---------------------------------------------------------------------------
// Account provisioning
// ---------------------------------------------------------------------------

// Twitter usernames allow [A-Za-z0-9_], DNS labels do not allow "_". Handles
// like "some_user" become "some-user.example.com".
export function twitterHandleToPdsLabel(twitterUsername: string): string {
  const label = twitterUsername
    .trim()
    .replace(/^@/, '')
    .toLowerCase()
    .replace(/_/g, '-')
    .replace(/[^a-z0-9-]/g, '')
    .replace(/^-+|-+$/g, '')
    .slice(0, 63);
  if (!label) {
    throw new Error(`Cannot derive a valid handle from Twitter username "${twitterUsername}"`);
  }
  return label;
}

interface XrpcErrorBody {
  error?: string;
  message?: string;
}

async function xrpc<T>(
  localUrl: string,
  method: 'GET' | 'POST',
  nsid: string,
  options: { body?: unknown; adminPassword?: string; params?: Record<string, string> } = {},
): Promise<T> {
  const query = options.params ? `?${new URLSearchParams(options.params)}` : '';
  const headers: Record<string, string> = { 'Content-Type': 'application/json' };
  if (options.adminPassword) {
    headers.Authorization = `Basic ${Buffer.from(`admin:${options.adminPassword}`).toString('base64')}`;
  }
  const res = await fetch(`${localUrl}/xrpc/${nsid}${query}`, {
    method,
    headers,
    body: options.body === undefined ? undefined : JSON.stringify(options.body),
  });
  const data = (await res.json().catch(() => ({}))) as T & XrpcErrorBody;
  if (!res.ok) {
    const err = new Error(`${nsid} failed: ${data.message || data.error || res.status}`);
    (err as Error & { xrpcError?: string }).xrpcError = data.error;
    throw err;
  }
  return data;
}

interface SqliteDbLike {
  prepare: (sql: string) => { run: (...params: unknown[]) => unknown; get: (...params: unknown[]) => unknown };
  close: () => void;
}

// Same runtime split as src/db.ts: bun:sqlite under bun (better-sqlite3's
// native module does not load there), better-sqlite3 under node.
export async function openSqliteDb(dbPath: string): Promise<SqliteDbLike> {
  if (typeof process.versions.bun === 'string') {
    const bunSqliteSpecifier = 'bun:sqlite';
    const sqliteModule = (await import(bunSqliteSpecifier)) as {
      Database: new (filename: string) => SqliteDbLike;
    };
    return new sqliteModule.Database(dbPath);
  }
  const betterSqliteModule = await import('better-sqlite3');
  return new betterSqliteModule.default(dbPath) as unknown as SqliteDbLike;
}

// The account is created with a phony local email and then marked verified by
// writing emailConfirmedAt directly into the PDS account database — no real
// mailbox or SMTP setup is needed.
export async function markEmailConfirmed(did: string): Promise<void> {
  const accountDb = path.join(PDS_DATA_DIR, 'account.sqlite');
  if (!fs.existsSync(accountDb)) {
    throw new Error(`PDS account database not found at ${accountDb}`);
  }
  const db = await openSqliteDb(accountDb);
  try {
    const backdated = new Date(Date.now() - 30 * 24 * 60 * 60 * 1000).toISOString();
    db.prepare('UPDATE account SET emailConfirmedAt = ? WHERE did = ? AND emailConfirmedAt IS NULL').run(
      backdated,
      did,
    );
  } finally {
    db.close();
  }
}

export async function provisionPdsAccount(
  settings: PdsSettings,
  twitterUsername: string,
  onProgress: ProvisionProgress = () => {},
): Promise<ProvisionResult> {
  const secrets = getPdsSecrets();
  if (!secrets) {
    throw new Error('PDS secrets missing from environment. Run `bun run cli -- setup-pds` first.');
  }
  const adminPassword = secrets.PDS_ADMIN_PASSWORD;
  const localUrl = `http://127.0.0.1:${settings.port}`;

  const label = twitterHandleToPdsLabel(twitterUsername);
  const handle = `${label}.${settings.hostname}`;
  // Phony address; never receives mail (verification is backdated in SQL).
  // The PDS validates email syntax including TLD, so bare hostnames like
  // "localhost" fall back to example.com.
  const emailDomain =
    settings.hostname.includes('.') && !isLocalHostname(settings.hostname) ? settings.hostname : 'example.com';
  const email = `${label}@${emailDomain}`;
  const password = randomBytes(18).toString('base64url');

  onProgress('Creating invite code');
  const invite = await xrpc<{ code: string }>(localUrl, 'POST', 'com.atproto.server.createInviteCode', {
    body: { useCount: 1 },
    adminPassword,
  });

  onProgress(`Creating account ${handle}`);
  try {
    const created = await xrpc<{ did: string }>(localUrl, 'POST', 'com.atproto.server.createAccount', {
      body: { email, handle, password, inviteCode: invite.code },
    });

    onProgress('Marking email as verified (backdated)');
    await markEmailConfirmed(created.did);

    return { twitterUsername, handle, did: created.did, password, existing: false };
  } catch (error) {
    const { xrpcError } = error as Error & { xrpcError?: string };
    const message = error instanceof Error ? error.message : '';
    const handleTaken =
      xrpcError === 'HandleNotAvailable' || xrpcError === 'AlreadyExists' || message.includes('Handle already taken');
    if (!handleTaken) {
      throw error;
    }

    // Account already exists (e.g. wizard re-run). Reset its password via the
    // admin API so we always end up with working credentials.
    onProgress(`Account ${handle} already exists — resetting password`);
    const resolved = await xrpc<{ did: string }>(localUrl, 'GET', 'com.atproto.identity.resolveHandle', {
      params: { handle },
    });
    await xrpc(localUrl, 'POST', 'com.atproto.admin.updateAccountPassword', {
      body: { did: resolved.did, password },
      adminPassword,
    });

    onProgress('Marking email as verified (backdated)');
    await markEmailConfirmed(resolved.did);

    return { twitterUsername, handle, did: resolved.did, password, existing: true };
  }
}

// ---------------------------------------------------------------------------
// Caddyfile generation (public deployments)
// ---------------------------------------------------------------------------

export function writeCaddyfile(settings: PdsSettings, contactEmail?: string): string {
  fs.mkdirSync(PDS_DATA_DIR, { recursive: true });
  const caddyfile = path.join(PDS_DATA_DIR, 'Caddyfile');
  const emailLine = contactEmail ? `\temail ${contactEmail}\n` : '';
  fs.writeFileSync(
    caddyfile,
    `{\n${emailLine}\ton_demand_tls {\n\t\task http://localhost:${settings.port}/tls-check\n\t}\n}\n\n` +
      `*.${settings.hostname}, ${settings.hostname} {\n\ttls {\n\t\ton_demand\n\t}\n\treverse_proxy http://localhost:${settings.port}\n}\n`,
  );
  return caddyfile;
}
